let fics = [
  {
    name: "Litte Cat",
    class: "SuperCorp",
    image: "",
    cap: 34,
    status: "Concluido",
    linkSpirit: "",
    linkWattpad: "",
  },
  {
    name: "Litte Cat",
    class: "SuperCorp",
    image: "",
    cap: 34,
    status: "Concluido",
    linkSpirit: "",
    linkWattpad: "",
  },
  {
    name: "Litte Cat",
    class: "SuperCorp",
    image: "",
    cap: 34,
    status: "Concluido",
    linkSpirit: "",
    linkWattpad: "",
  },
  {
    name: "Insuperavel",
    class: "SwanQueen",
    image: "",
    cap: 34,
    status: "Concluido",
    linkSpirit: "",
    linkWattpad: "",
  },
  {
    name: "Domino",
    class: "Outros",
    image: "",
    cap: 34,
    status: "Concluido",
    linkSpirit: "",
    linkWattpad: "",
  },
];
